// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adfitnytnodsmgxivkai.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkZml0bnl0bm9kc21neGl2a2FpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NzI5MjYsImV4cCI6MjA2NDQ0ODkyNn0.1picBJg1JNp0WEPeku7d3gYVXZrzsLJ12NpW25YE7vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);